# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/XilinxSdk/verilog-miniproject/vivado/sdcard_led_switch/sdcard_led_switch.srcs/sources_1/bd/sdcard_led_switch/ip/sdcard_led_switch_xbar_0/sdcard_led_switch_xbar_0.xci
# IP: The module: 'sdcard_led_switch_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/XilinxSdk/verilog-miniproject/vivado/sdcard_led_switch/sdcard_led_switch.srcs/sources_1/bd/sdcard_led_switch/ip/sdcard_led_switch_xbar_0/sdcard_led_switch_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sdcard_led_switch_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: E:/XilinxSdk/verilog-miniproject/vivado/sdcard_led_switch/sdcard_led_switch.srcs/sources_1/bd/sdcard_led_switch/ip/sdcard_led_switch_xbar_0/sdcard_led_switch_xbar_0.xci
# IP: The module: 'sdcard_led_switch_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/XilinxSdk/verilog-miniproject/vivado/sdcard_led_switch/sdcard_led_switch.srcs/sources_1/bd/sdcard_led_switch/ip/sdcard_led_switch_xbar_0/sdcard_led_switch_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sdcard_led_switch_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
