# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/sdcard_led_switch/sdcard_led_switch.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sdcard_led_switch || ORIG_REF_NAME==sdcard_led_switch}]

# IP: bd/sdcard_led_switch/ip/sdcard_led_switch_processing_system7_0_0/sdcard_led_switch_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sdcard_led_switch_processing_system7_0_0 || ORIG_REF_NAME==sdcard_led_switch_processing_system7_0_0}]

# IP: bd/sdcard_led_switch/ip/sdcard_led_switch_axi_gpio_0_1/sdcard_led_switch_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sdcard_led_switch_axi_gpio_0_1 || ORIG_REF_NAME==sdcard_led_switch_axi_gpio_0_1}]

# IP: bd/sdcard_led_switch/ip/sdcard_led_switch_ps7_0_axi_periph_0/sdcard_led_switch_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sdcard_led_switch_ps7_0_axi_periph_0 || ORIG_REF_NAME==sdcard_led_switch_ps7_0_axi_periph_0}]

# IP: bd/sdcard_led_switch/ip/sdcard_led_switch_rst_ps7_0_100M_0/sdcard_led_switch_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sdcard_led_switch_rst_ps7_0_100M_0 || ORIG_REF_NAME==sdcard_led_switch_rst_ps7_0_100M_0}]

# IP: bd/sdcard_led_switch/ip/sdcard_led_switch_axi_gpio_1_0/sdcard_led_switch_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sdcard_led_switch_axi_gpio_1_0 || ORIG_REF_NAME==sdcard_led_switch_axi_gpio_1_0}]

# IP: bd/sdcard_led_switch/ip/sdcard_led_switch_xbar_0/sdcard_led_switch_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sdcard_led_switch_xbar_0 || ORIG_REF_NAME==sdcard_led_switch_xbar_0}]

# IP: bd/sdcard_led_switch/ip/sdcard_led_switch_auto_pc_0/sdcard_led_switch_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sdcard_led_switch_auto_pc_0 || ORIG_REF_NAME==sdcard_led_switch_auto_pc_0}]

# XDC: bd/sdcard_led_switch/sdcard_led_switch_ooc.xdc
